language: c

script:
  - echo 'deploying ...'
  - echo '' >> $STATUSFILE
  - echo '<!--' >> $STATUSFILE
  - echo 'last deployed at' >> $STATUSFILE
  - date >> $STATUSFILE
  - echo 'from commit $TRAVIS_COMMIT' >> $STATUSFILE
  - echo 'by $USER' >> $STATUSFILE
  - echo '-->' >> $STATUSFILE

env:
  global:
  - STATUSFILE=index.html
  - secure: MTiTfLQ2cUINynl7ucMved5JDcyjQTfnR0je57GuiGJtD+9+cuGO+hgNvdh3e6i2q22g5LSlcFIU7DfTy+cev19UhyB4m9FK6py79DoNtoPSmYrpaPaZStIbH9A8hkDz6mbCXHCLkhjg38KA06+UA+ltBbusdHUIZ0+2M4q++ucSe6X6jHDdILsySOas/I6Gn5liV5MlYmXGo0/Zq27e+XypPrXefPXNuNUSJKsWsPAJHr2A1lEbEI7RxYdNzfSoQ1szDu9Fq4mFO2n9qZfOejjhah0xCsdYcSGlRoV+ogbRhRvhzytzd7cNHmFWJ3NcAQGysA+MVMSXOpifXvEuBFCCZzUM1ElCiwcpkl9Jt6OHyJUKXA8bFW530giGhUY8USoyBjV5c5orQbR37vSGDheGEopMEygUHoPgG4DgurLH+ZYJpRP3mdXNe3Eq4rChirioFWeIFZ/aBm9O7NmQN6YVm6urOJT8H5Ii65KiNxUFuKKEgpDWyrb2OZaA+LmscYIK9PYDUcHBynB8Aq9//aXEzRwvAMI4+w04qt01Kh2Iny9HohPb42UjM/lRjhRq12nq3fyz+Hvi6MoYu125CJltTl8+xCFvTPbLHjbRAytUXhHyh5qoM8R9uVAat6wR3GnFRHlFkvuMLoGW6dLVQhb0KNJWBW3nHyGl/YsAzaE=
  - secure: CbB3zNCHqzoIlbj9QC8fD2nv+8If8cuyA8N+qA7WReYLqy/j7EB6d++dvN3a0PbxPLW7/VRJt8jwIQ8VnIU7xBfB+kePcXNsSR4joJ8Ygb0789SLWVEkgJZN+kbu/zb6cxIZcU03/OAXWKIBGskPiC60dUPlnXPx9kaFT67X5wmIZPXKPr+RH6YtyrL8nTNry3L1zy4HOkRcP8dL5yRDNWLRJ4Ojyfu52TBYJ7HHszLU834p5pN4EenFaPAHpDWAWoP44X51Oj89mf5gPacCbl8/ZTOgKTD8CZl7m0JhhAe1Yu6ata5N75r6fjT1VYlzn6AYxTordjY6tDb7CzqpF9f9JD+N4UNso5hpzyS+v/h6C3w/BWTutTNgWStsP3DJc6j4bc0ZzswX+9BnO8gelMEisk00VyOzwFv7cV6RZk+m+ycOso6oHqNrcvuOOBUiONou9VGXc0R6IS026ENMW2iHU/tr5OBKORT3xosE2gxe4qeZmHqwVhpaOreRbZgVlMuD6dpjsN9uf5p11goYuNbdVsrwLRr7vhEd7nmJ57v7zGAUSD8HrkyZ2/CWWDOKRFaY0XjjO4sgdGF+S1iAtrOoQhJUAsCXvlGGntEWW5QLZY8NudcGzvTid2EObtQtFm0byNYn1QnfNosyqWq634FMvenX+1XNNvWiLiKGd4Q=
  - secure: iyEzZ7G5lb9sQrIxcmgiThsPDvDE+zHdrkR28Vbwl8twYdf5LgiDpgJIVoCacJGkibCLqA4uyX9peb/P7i88jlqSBaNC2DTNIqvI+QJ9k/EaaJ6Ae/PySYup8wt1fEYMu4pbQ4hYiZrv6W8nFFJSxNm0YFTrZMDNfa1IYtR3B5vyvkrFj62nqDzbhdfAprwM6cl9aHZh44a/UrRIOocH0P+Wt9qWlM77od57OwA15YG0g4vQ79x633KkzwagjXpf6hqbweANSCW5G07KvS+cK7QBqeFdnMOQCsq9Kp5TXDNKmrtFkxJw4QLIJzGH8J8Vkm0y4KjupDYrCmqsVZoDtZupNuSUKQD6cO6bcTLd2fWJI/9Vv4F9aEm/Z7sRBrDc8XQMnk0Ye2xnyCy/84V3UQM4P4nn+yW7o0sU15Icz0y/BN2SL6LiTDmNIKJDAopHzrvAtVVhkPNLNqFAil1wu4u9LNU8lYCCSypae/RAfz2Oe28Jsw2VDM94HJ534CUxkwao7bgsa0fIyoZW3lb/uRFtl/NCs9yXG/l2viouT0z5rI01jaitA0w+0vRSyEDZ4r3QBF9HRL/yaToZslGmxwCmhG4WTKiqwL7Q9pSa2zIfF1M2RzdPJDUCkIq1VKaGjZgS7ZcTu5JieBmctSH1hCT9LhI5gyowqFHxgGkVF9Y=

deploy:
  provider: script
  script: find . -not -path '*/\.*' -type f -exec echo {} \; -exec curl -u $FTPUSER:$FTPPASSWORD --ftp-create-dirs -T {} ftp://$FTPSERVER/\{\} \;
